interface CloudflareEnv {
  APPLE_MUSIC_NOW_PLAYING_KV: KVNamespace;

  TURNSTILE_SECRET_KEY: string;
  NEXT_PUBLIC_TURNSTILE_SITE_KEY: string;
  NEXT_PUBLIC_PRODUCTION_BASE_URL: string;
  NEXT_PUBLIC_APPLE_DEVELOPER_TOKEN: string;
  NEXT_PUBLIC_APPLE_MUSIC_APP_NAME: string;
}
